//
//  PRXLogger.h
//  TapPointSDK
//
//  Created by Łukasz Niedziałek on 26/09/2018.
//  Copyright © 2018 Proxama Solutions Ltd. All rights reserved.
//

/**
 * A PRXLogger is a static class used to received logs generated by TapPoint SDK.
 */
@interface PRXLogger : NSObject

/**
 * Returns content of a log file filled with the logs generated by TapPoint SDK.
 *
 * @return NSString consisting of the log messages.
 */
+ (NSString *) getLogs;

- (instancetype) init NS_UNAVAILABLE;

@end
